/**
 * models/Notification.js — in-app notification for one recipient.
 *
 * Generated by the notification service on approvals, comments, likes, pins, and
 * event changes (architecture.md § Notification layer).
 */
const mongoose = require('mongoose');
const { NOTIFICATION_TYPES } = require('../utils/constants');

const notificationSchema = new mongoose.Schema(
  {
    recipient: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true, index: true },
    actor: { type: mongoose.Schema.Types.ObjectId, ref: 'User', default: null },
    type: { type: String, enum: Object.values(NOTIFICATION_TYPES), required: true },
    message: { type: String, required: true, trim: true, maxlength: 300 },
    community: { type: mongoose.Schema.Types.ObjectId, ref: 'Community', default: null },
    post: { type: mongoose.Schema.Types.ObjectId, ref: 'Post', default: null },
    comment: { type: mongoose.Schema.Types.ObjectId, ref: 'Comment', default: null },
    event: { type: mongoose.Schema.Types.ObjectId, ref: 'Event', default: null },
    /** Client-side route to open when the notification is clicked. */
    link: { type: String, trim: true, default: '' },
    isRead: { type: Boolean, default: false, index: true },
    readAt: { type: Date, default: null },
  },
  { timestamps: true },
);

notificationSchema.index({ recipient: 1, isRead: 1, createdAt: -1 });

module.exports = mongoose.model('Notification', notificationSchema);
