/**
 * components/ui/icons.js — Centralized Lucide icon exports for the entire app.
 * Tree-shakable, consistent, professional icons throughout.
 */
export {
  // Navigation & Layout
  LayoutDashboard as DashboardIcon,
  Newspaper as FeedIcon,
  Users as CommunitiesIcon,
  Users as MembersIcon,
  Calendar as EventsIcon,
  Bell as NotificationsIcon,
  Shield as ModerationIcon,
  User as ProfileIcon,
  Settings as SettingsIcon,
  BarChart2 as AdminIcon,
  LogOut as SignOutIcon,
  ChevronLeft as CollapseIcon,
  ChevronRight as ExpandIcon,
  Sun as LightThemeIcon,
  Moon as DarkThemeIcon,
  Search as SearchIcon,
  Eye as ShowPasswordIcon,
  EyeOff as HidePasswordIcon,
  Menu as MenuIcon,
  X as CloseIcon,

  // Actions
  Plus as AddIcon,
  Edit2 as EditIcon,
  Trash2 as DeleteIcon,
  Pin as PinIcon,
  PinOff as UnpinIcon,
  Heart as LikeIcon,
  HeartOff as UnlikeIcon,
  MessageSquare as CommentIcon,
  Share2 as ShareIcon,
  Flag as ReportIcon,
  Bookmark as BookmarkIcon,
  Copy as CopyIcon,
  Download as DownloadIcon,
  Upload as UploadIcon,
  Zap as ZapIcon,

  // Status & Feedback
  CheckCircle as SuccessIcon,
  AlertTriangle as WarningIcon,
  AlertCircle as ErrorIcon,
  Info as InfoIcon,
  Loader2 as LoadingIcon,
  Check as CheckIcon,
  X as CrossIcon,

  // Community & Social
  UserPlus as InviteIcon,
  UserMinus as RemoveMemberIcon,
  UserCheck as ApproveIcon,
  UserX as RejectIcon,
  ShieldCheck as VerifiedIcon,
  Lock as PrivateIcon,
  Lock as LockIcon,
  Unlock as PublicIcon,
  Globe as PublicWorldIcon,
  Globe as GlobeIcon,
  Home as LocationIcon,
  MapPin as MapPinIcon,
  Building as BuildingIcon,
  Building2 as CommunityIcon,
  Building2 as Building2Icon,
  Mail as EmailIcon,
  Mail as MailIcon,

  // Events & Calendar
  Calendar as CalendarIcon,
  CalendarPlus as CreateEventIcon,
  CalendarCheck as RsvpIcon,
  CalendarX as CancelEventIcon,
  Clock as TimeIcon,
  MapPin as VenueIcon,

  // Content & Media
  Image as ImageIcon,
  Video as VideoIcon,
  FileText as PostIcon,
  FileImage as ImagePostIcon,
  FileVideo as VideoPostIcon,
  FileAudio as AudioPostIcon,
  Paperclip as AttachmentIcon,
  Link as LinkIcon,
  Link2 as ExternalLinkIcon,

  // Admin & Moderation
  BadgeCheck as ApprovedIcon,
  BadgeX as RejectedIcon,
  BadgeAlert as PendingIcon,
  Gavel as ModerationIcon2,
  Ban as BanIcon,
  ShieldAlert as ReportIcon2,
  Eye as ViewIcon,
  EyeOff as HideIcon,
  Tag as TagIcon,
  Shield as ShieldIcon,

  // UI Elements
  ChevronDown as ChevronDownIcon,
  ChevronUp as ChevronUpIcon,
  ChevronLeft as ChevronLeftIcon,
  ChevronRight as ChevronRightIcon,
  MoreHorizontal as MoreIcon,
  MoreVertical as MoreVerticalIcon,
  Filter as FilterIcon,
  SortAsc as SortIcon,
  Grid as GridIcon,
  List as ListIcon,
  RefreshCw as RefreshIcon,
  RotateCcw as UndoIcon,
  ArrowRight as NextIcon,
  ArrowLeft as PrevIcon,

  // Communication
  Send as SendIcon,
  Inbox as InboxIcon,
  Bell as NotificationBellIcon,
  BellOff as NotificationOffIcon,
  Mic as VoiceIcon,
  MicOff as MuteIcon,
  Megaphone as MegaphoneIcon,

  // Settings & Preferences
  SlidersHorizontal as SlidersIcon,
  ToggleLeft as ToggleOffIcon,
  ToggleRight as ToggleOnIcon,
  Key as KeyIcon,
  Shield as SecurityIcon,
  Palette as ThemeIcon,
  Languages as LanguageIcon,
  HelpCircle as HelpIcon,
  Info as AboutIcon,
  Sparkles as SparklesIcon,
  Briefcase as SuitcaseIcon,
} from 'lucide-react';
